// <auto-generated />
namespace hsscms_bo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Org_names : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Org_names));
        
        string IMigrationMetadata.Id
        {
            get { return "201811091412376_Org_names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
